import {defineType, defineField} from 'sanity'

export default defineType({
  name: 'area',
  title: 'Çalışma Alanı (Practice Area)',
  type: 'document',
  groups: [
    {name: 'tr', title: 'Türkçe', default: true},
    {name: 'en', title: 'English'},
    {name: 'meta', title: 'Genel'},
  ],
  fields: [
    defineField({
      name: 'name',
      title: 'Alan Adı (TR)',
      type: 'string',
      group: 'tr',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'name_en',
      title: 'Area Name (EN)',
      type: 'string',
      group: 'en',
    }),
    defineField({
      name: 'shortDescription',
      title: 'Kısa Açıklama (TR)',
      type: 'text',
      rows: 2,
      group: 'tr',
      description: 'Anasayfadaki kart açıklaması (1-2 cümle).',
    }),
    defineField({
      name: 'shortDescription_en',
      title: 'Short Description (EN)',
      type: 'text',
      rows: 2,
      group: 'en',
    }),
    defineField({
      name: 'description',
      title: 'Açıklama (TR)',
      type: 'text',
      rows: 4,
      group: 'tr',
      description: 'Çalışma Alanları sayfasındaki uzun açıklama.',
    }),
    defineField({
      name: 'description_en',
      title: 'Description (EN)',
      type: 'text',
      rows: 4,
      group: 'en',
    }),
    defineField({
      name: 'tags',
      title: 'Etiketler (TR)',
      type: 'array',
      of: [{type: 'string'}],
      options: {layout: 'tags'},
      group: 'tr',
    }),
    defineField({
      name: 'tags_en',
      title: 'Tags (EN)',
      type: 'array',
      of: [{type: 'string'}],
      options: {layout: 'tags'},
      group: 'en',
    }),
    defineField({
      name: 'nedirTitle',
      title: '"Nedir?" Başlığı (TR)',
      type: 'string',
      group: 'tr',
    }),
    defineField({
      name: 'nedirTitle_en',
      title: '"What is it?" Title (EN)',
      type: 'string',
      group: 'en',
    }),
    defineField({
      name: 'nedirContent',
      title: '"Nedir?" Açıklaması (TR)',
      type: 'text',
      rows: 5,
      group: 'tr',
    }),
    defineField({
      name: 'nedirContent_en',
      title: '"What is it?" Content (EN)',
      type: 'text',
      rows: 5,
      group: 'en',
    }),
    defineField({
      name: 'steps',
      title: 'Süreç Adımları',
      type: 'array',
      group: 'meta',
      of: [
        {
          type: 'object',
          name: 'step',
          fields: [
            {name: 'title', title: 'Adım Başlığı (TR)', type: 'string'},
            {name: 'title_en', title: 'Step Title (EN)', type: 'string'},
            {name: 'description', title: 'Adım Açıklaması (TR)', type: 'text', rows: 2},
            {name: 'description_en', title: 'Step Description (EN)', type: 'text', rows: 2},
          ],
          preview: {select: {title: 'title'}},
        },
      ],
    }),
    defineField({
      name: 'order',
      title: 'Sıra',
      type: 'number',
      group: 'meta',
      description: 'Listede gösterim sırası (1 = en üstte).',
      validation: (r) => r.required(),
      initialValue: 1,
    }),
  ],
  preview: {
    select: {title: 'name', order: 'order'},
    prepare: ({title, order}) => ({title, subtitle: `#${order}`}),
  },
  orderings: [
    {title: 'Sıra (artan)', name: 'orderAsc', by: [{field: 'order', direction: 'asc'}]},
  ],
})
